# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orbital_radius_in_au', models.DecimalField(decimal_places=3, default=1, max_digits=20)),
                ('orbital_period_in_years', models.DecimalField(decimal_places=3, default=1, max_digits=20)),
                ('earth_radii', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('earth_masses', models.DecimalField(decimal_places=3, default=1, max_digits=13)),
                ('temperature_in_kelvin', models.IntegerField(default=273)),
                ('percentage_of_water', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlanetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=20)),
                ('x_coord', models.DecimalField(decimal_places=3, max_digits=20)),
                ('y_coord', models.DecimalField(decimal_places=3, max_digits=20)),
                ('z_coord', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genus', models.CharField(max_length=200, null=True)),
                ('species', models.CharField(default='', max_length=200)),
                ('population', models.BigIntegerField(default=1000)),
                ('conservation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.ConservationType')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpectralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orbital_radius_in_au', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('orbital_period_in_years', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('solar_radii', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('solar_masses', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('temperature_in_kelvin', models.IntegerField(default=5700)),
                ('solar_luminosities', models.DecimalField(decimal_places=3, default=1, max_digits=13)),
                ('solar_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SolarSystem')),
                ('spectral_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SpectralType')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='species',
            name='species_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SpeciesType'),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.PlanetType'),
        ),
        migrations.AddField(
            model_name='planet',
            name='species',
            field=models.ManyToManyField(to='zookapp.Species'),
        ),
        migrations.AddField(
            model_name='planet',
            name='stars',
            field=models.ManyToManyField(to='zookapp.Star'),
        ),
    ]
