# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=20)),
                ('reference_point', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('distance',),
            },
        ),
        migrations.CreateModel(
            name='Hof',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=20)),
                ('reference_point', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orbital_radius_in_au', models.DecimalField(decimal_places=3, default=1, max_digits=20)),
                ('earth_radii', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('earth_masses', models.DecimalField(decimal_places=3, default=1, max_digits=13)),
                ('temperature_in_kelvin', models.IntegerField(default=273)),
                ('percentage_of_water', models.IntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('orbital_radius_in_au',),
            },
        ),
        migrations.CreateModel(
            name='PlanetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShipCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShipSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x_coord', models.DecimalField(decimal_places=3, max_digits=20)),
                ('y_coord', models.DecimalField(decimal_places=3, max_digits=20)),
                ('z_coord', models.DecimalField(decimal_places=3, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/solarsystems/')),
            ],
        ),
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=100000)),
                ('agility', models.IntegerField(default=5)),
                ('speed', models.IntegerField(default=200)),
                ('boost', models.IntegerField(default=300)),
                ('jump_range', models.DecimalField(decimal_places=2, default=10, max_digits=20)),
                ('hardpoints', models.CharField(default='1 small', max_length=200)),
                ('compartments', models.CharField(default='2xClass 2, 2xClass 1', max_length=200)),
                ('cargo_space', models.IntegerField(default=8)),
                ('fuel_space', models.IntegerField(default=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/solarsystems/')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.ShipCreator')),
                ('ship_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.ShipType')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.ShipSize')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genus', models.CharField(max_length=200, null=True)),
                ('species', models.CharField(default='', max_length=200)),
                ('population', models.BigIntegerField(default=1000)),
                ('is_it_spacefaring', models.CharField(blank=True, max_length=200, null=True)),
                ('conservation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.ConservationType')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpectralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orbital_radius_in_au', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('orbital_period_in_years', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('solar_radii', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('solar_masses', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('temperature_in_kelvin', models.IntegerField(default=5700)),
                ('visual_magnitude', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('solar_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SolarSystem')),
                ('spectral_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SpectralType')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.BigIntegerField(default=1000)),
            ],
            options={
                'ordering': ('-population',),
            },
        ),
        migrations.CreateModel(
            name='StationEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='StationGovernment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAllegiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(default='Independent', max_length=200)),
                ('color', models.CharField(default='df0', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='stationfaction',
            name='government_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationGovernment'),
        ),
        migrations.AddField(
            model_name='station',
            name='economy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationEconomy'),
        ),
        migrations.AddField(
            model_name='station',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationFaction'),
        ),
        migrations.AddField(
            model_name='station',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Planet'),
        ),
        migrations.AddField(
            model_name='station',
            name='services',
            field=models.ManyToManyField(to='zookapp.StationService'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationType'),
        ),
        migrations.AddField(
            model_name='species',
            name='species_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SpeciesType'),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='allegiance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SystemAllegiance'),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationFaction'),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='galaxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Galaxy'),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='hof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Hof'),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SystemPermit'),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SystemSecurity'),
        ),
        migrations.AddField(
            model_name='planet',
            name='economy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationEconomy'),
        ),
        migrations.AddField(
            model_name='planet',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationFaction'),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.PlanetType'),
        ),
        migrations.AddField(
            model_name='planet',
            name='ring_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.RingType'),
        ),
        migrations.AddField(
            model_name='planet',
            name='species',
            field=models.ManyToManyField(to='zookapp.Species'),
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Star'),
        ),
    ]
