# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='stars',
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Star'),
        ),
    ]
