# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0002_auto_20160301_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ('orbital_radius_in_au',)},
        ),
        migrations.AlterModelOptions(
            name='solarsystem',
            options={'ordering': ('distance',)},
        ),
    ]
