# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0002_species_hof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='hof',
        ),
        migrations.AddField(
            model_name='species',
            name='is_it_spacefaring',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
