# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0003_auto_20160318_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
            options={
                'ordering': ('distance',),
            },
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='galaxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Galaxy'),
        ),
    ]
