# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0004_planet_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.BigIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StationEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='economy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationEconomy'),
        ),
        migrations.AddField(
            model_name='station',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.Planet'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationType'),
        ),
    ]
