# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0005_auto_20160326_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
