# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0005_auto_20160303_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='economy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationEconomy'),
        ),
    ]
