# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0006_auto_20160326_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='reference_point',
            field=models.CharField(default='Sol', max_length=200),
            preserve_default=False,
        ),
    ]
