# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0006_species_economy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='economy',
        ),
        migrations.AddField(
            model_name='planet',
            name='economy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.StationEconomy'),
        ),
    ]
