# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0008_auto_20160303_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('-population',)},
        ),
    ]
