# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0008_remove_planet_orbital_period_in_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='solar_luminosities',
        ),
    ]
