# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0009_remove_star_solar_luminosities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarsystem',
            options={},
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='distance',
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='x_coord',
            field=models.FloatField(),
        ),
    ]
