# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0009_auto_20160303_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='services',
            field=models.ManyToManyField(to='zookapp.StationService'),
        ),
    ]
