# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0010_auto_20160327_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem',
            name='x_coord',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
