# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0010_auto_20160303_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zookapp.SystemSecurity'),
        ),
    ]
