# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0011_auto_20160327_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectraltype',
            options={'ordering': ('name',)},
        ),
    ]
