# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zookapp', '0011_auto_20160303_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='visual_magnitude',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
    ]
